
export const FACULTY = {
  COMMERCE_AND_MANAGEMENT: 'Faculty of Commerce and Management',
  HOTEL_AND_TOURISM_MANAGEMENT: 'Faculty of Hotel and Tourism Management',
  ALLIED_HEALTH_SCIENCES: 'Faculty of Allied Health Sciences',
  AGRICULTURAL_SCIENCES: 'Faculty of Agricultural Sciences',
  APPLIED_AND_BASIC_SCIENCES: 'Faculty of Applied and Basic Sciences',
  DESIGN: 'Faculty of Design',
  MASS_COMMUNICATIONS_AND_MEDIA_TECHNOLOGY: 'Faculty of Mass Communications and Media Technology',
  BEHAVIOURAL_SCIENCES: 'Faculty of Behavioural Sciences',
  LAW: 'Faculty of Law',
  EDUCATION: 'Faculty of Education',
  DENTAL_SCIENCES: 'Faculty of Dental Sciences',
  NATUROPATHY_AND_YOGIC_SCIENCES: 'Faculty of Naturopathy and Yogic Sciences',
  INDIAN_MEDICAL_SCIENCES: 'Faculty of Indian Medical Sciences',
  NURSING: 'Faculty of Nursing',
  PHARMACY: 'Faculty Of Pharmacy',
  PHYSIOTHERAPY: 'Faculty of Physiotherapy',
  MEDICAL_HEALTH_SCIENCES: 'Faculty of Medical Health Sciences',
  ENGINEERING_AND_TECHNOLOGY: 'Faculty of Engineering and Technology',
  HUMANITIES_SOCIAL_SCIENCES_AND_LIBERAL_ARTS: 'Faculty of Humanities Social Sciences and Liberal Arts',
};
